import type { Metadata } from "next";
import { Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import VideoBanner from "@/components/VideoBanner";

const inter = Inter({ subsets: ["latin"], display: "swap" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  relative text-white min-h-dvh grid-layout`}
      >
        <div className="col-[2/4]">
          <Navbar />
          <VideoBanner />
        </div>
        <main className="grid-center">{children}</main>
      </body>
    </html>
  );
}
